config/routes.rb
######API#######
require 'api_constraints'

Rails.application.routes.draw do


  #Aquí creamos rutas para proveer la API de la aplcación, para ver más detalles acceder a:
    # http://railscasts.com/episodes/350-rest-api-versioning?view=asciicast
  namespace :api, defaults: {format: 'json'} do

    #Archivos relevantes para la API
    ## /lib/api_constraints
    ## /app/controllers/api  (todo lo que esta dentro de esa carpeta)

    # Para la version 1 tenemos este bloque con api constraints especificamos la versión
    # y si es que esta es la que se ocupa por default
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      #Aquí defeinimos las rutas que queremos proveer
      #por ahora tenemos disponibles los proyectos, tareas y login de usuario
      get '/locks/all' => 'locks#all'
      resources :projects, only: [:index] do
        resources :tasks, only: [:index,:update,:show] do
          get 'all', on: :collection
          put 'update_gantt', on: :member, action:'update_gantt'
          delete 'update_gantt', on: :member, action:'destroy'
          post 'update_gantt', on: :collection, action:'create'
          resources :comments, only: [:create]
        end
        get 'all', on: :collection
      end

      #Métodos para usuarios
      post 'users/login', to: 'users#login'
      delete 'users/logout', to: 'users#logout'

      #Métodos de progresos
      get '/progress/estimated_in_resources_by_week' 
      get '/progress/real_in_resources_by_week' 
      get '/progress/estimated_in_days_by_week'
      get '/progress/real_in_days_by_week' 
      get '/progress/all_progress'

      get '/progress/performance_in_resources_by_week'
      get '/progress/performance_in_one_by_week'
      post '/push/send_token'

      
      get '/progress/performance_estimated_by_week'
      get '/progress/performance_real_by_week'

    end
  end

#######termino API#####
  
  # Página de errores
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #usuarios con gema devise
  devise_for :users


  #Resources genera todas las rutas CRUD para cada uno de estos objetos
  resources :projects do
    get 'delete'
    get 'second_indicators'
    get 'tree_view'
    get 'add_tree_view_column'
    get 'indicators'
    get 'export'
    get 'kanban_board', to: 'kanban_board#index', as: :kanban_board_index
    get 'gantt', to: 'gantt#index'

    resources :users, only: [:index]
    resources :tasks do
      resources :reports
      resources :comments

    end
  end

  resources :tasks do
    get 'delete_confirmation'
    get 'fast_report'
  end

  get 'gantt', to: 'gantt#index'
  get 'update_tree_view', to: 'tasks#update_tree_view'
  
  # get 'kanban_board_index', to: 'kanban_board#index'
  get 'gantt', to: 'gantt#index'

  resources :comments
  resources :reports
  resources :assignments
  resources :users



  resources :enterprises do
    resources :projects
    resources :users
  end

  namespace :kanban_board do
    get 'index'
    get 'update_item_partial'
  end




  root 'users#root_router'
end

app/models/user.rb
class User < ActiveRecord::Base
	# pertenece a una empresa
	belongs_to :enterprise

	# es dueño de maximo una empresa
	has_one :owned_enterprise, class_name:'Enterprise', foreign_key:'boss_id'

	#relación con proyectos
	has_many :assignments, dependent: :destroy
	has_many :projects, through: :assignments
	#puede tener muchas tareas
	has_many :tasks
	has_many :reports
	#tiene una api key, esta key debe eliminarse si el usuario es destruido
	has_many :api_key, dependent: :destroy 

	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
	ROLES = %i[super_admin admin last_planner observer]

	def f_name
		name + ' ' + last_name
	end

	def is_boss
		if self.super_admin
			false
		elsif self.enterprise.boss == self
			true
		else
			false
		end
	end

	def role_in_project(project)
		if !is_boss && !super_admin
			role = Assignment.where(user_id: id, project_id: project.id).first.role
			if role == 1
				return 'Administrador'
			elsif role == 2
				return 'Last planner'
			end
		else
			return 'Jefe'
		end

	end

	def tasks_by_project(project_id)
		self.tasks.where(project_id: project_id)
	end


	# Retorna true si el usuario esta asignado a algun proyecto del current user
	def show_user(cuser)
		cuser.projects.each do |cup|
			if self.projects.to_a.empty? && !cuser.lp?
				return true
			else
				self.projects.each do |up|
					if up.id == cup.id
						return true
					end
				end
			end
		end
		return false
	end

	def asignar(cuser)
		if cuser.role == 'super_admin'
			return true
		elsif cuser.lp? or cuser.role == 'observer'
			return false
		else
			if self.role == 'super_admin'
				return false
			else
				return true
			end
		end		
	end

	# Metodo que asigna una imagen a los usuarios.
	def image(n)
		if n < 7
			return 'u'+n.to_s+'.jpg'
		else
			self.image(n-7)
		end
	end

	########################### KANBAN
	def kanban(project)
		tasks_hash = {}
		inactive_tasks = []
		in_progress_tasks = []
		done_tasks = []

		project.kanban[:inactive_tasks].each do |t|
			if role_in_project(project) == 'Administrador' || is_boss
				inactive_tasks << t
			elsif role_in_project(project) == 'Last planner' && t.user_id == id
				inactive_tasks << t
			end
		end

		project.kanban[:in_progress_tasks].each do |t|
			if role_in_project(project) == 'Administrador' || is_boss
				in_progress_tasks << t
			elsif role_in_project(project) == 'Last planner' && t.user_id == id
				in_progress_tasks << t
			end
		end

		project.kanban[:done_tasks].each do |t|
			if role_in_project(project) == 'Administrador' || is_boss
				done_tasks << t
			elsif role_in_project(project) == 'Last planner' && t.user_id == id
				done_tasks << t
			end
		end

		tasks_hash[:inactive_tasks] = inactive_tasks
		tasks_hash[:in_progress_tasks] = in_progress_tasks
		tasks_hash[:done_tasks] = done_tasks

		return tasks_hash
	end

	######################## FIN KANBAN

	# PERMISOS
	def can_edit_task(task)
		if super_admin
			return true
		elsif is_boss && task.enterprise == enterprise 
			return true
		elsif a = Assignment.where(user_id: id, project_id: task.project.id).first
			if a.role == 1
				return true
			end
		else
			return false
		end
	end

	def can_report_task(task)
		if super_admin
			true
		elsif a = Assignment.where(user_id: id, project_id: task.project.id).first
			# El admin puede reportar cualquier tarea
			if a.role == 1
				return true

			# El lastplanner puede reportar solo sus propias tareas
			elsif task.user == self
				return true
			end
		else
			return false
		end
	end

	def can_edit_project(project)
		if super_admin
			return true
		elsif is_boss && project.enterprise == enterprise 
			return true
		elsif a = Assignment.where(user_id: id, project_id: project.id).first
			if a.role == 1
				return true
			end
		else
			return false
		end
	end

end

app/controllers/api/v1/users_controller.rb
#Aquí definimos las respuestas a las llamadas de la api
module Api
    module V1
        class UsersController < ActionController::Base
            #Con esto definimos como queremos entregar la respuesta.
            respond_to :json

            # Este método retorna el token del usuario y la información necesaria para
            # la aplicación mobile
            def login
            	user = User.where(email: params[:email]).first
                if user
                    if user.valid_password?(params[:password])
                        tok = ApiKey.create!
                        if tok
                            user.api_key << tok
                            user.save
                            tok.user = user
                            tok.expire_date = Time.now + 1.day
                            tok.save
                            render json: {:token=> tok.access_token, :username=> user.name, :role=> user.role, :user_id=> user.id}
                        end
                    else 
                        #Password malo
                        render nothing: :true , status: 401
                    end
                else
                    #Mail malo
                    render nothing: :true, status: 401
                end
            end

            #Este método borra el token que tiene el usuario
            def logout
                token = request.headers["Authorization"]
                set_api_key(token)
                if @ak
                    @ak.destroy
                end
                render nothing: :true, status: 200
            end


            private

            def set_api_key(token)
                @ak = ApiKey.find_by_access_token(token)
            end

        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  #manda los proyectos y el usuario que se quiere asignar a proyectos a la vista assign
  def assign
    @projects = Project.all
    @user = User.find(params[:id])
  end

  # GET /users
  # GET /users.json
  def index
    if @project
      @users = @project.users
    elsif @enterprise
      @users = @enterprise.users
    end
  end

  def new
    @user = User.new(enterprise_id: params[:enterprise_id])
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end



  def create
    @user = User.new(user_params)
    
    # @user.name = @user.name.camelize
    respond_to do |format|
      if @user.save
        format.html { redirect_to request.referer }
        format.json { render :show, status: :created, location: '/users' }
      else
        format.html { render 'new' } ## Specify the format in which you are rendering "new" page
        format.json { render json: @user.errors }
      end
    end
  end

  def show
    @users = User.all
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    if @user.present?
      @user.destroy

      respond_to do |format|
        format.html { redirect_to :back }
        format.json { head :no_content }
      end
    end
  end

  def update

    # required for settings form to submit when password is left blank
    if user_params[:password].blank?
      params[:user].delete(:password)
    end
    @user = User.find(params[:id])
    #Creo un nuevo hash para guardar el nombre con mayuscula
    new_user_params = user_params
    new_user_params[:name] = user_params[:name].camelize
    respond_to do |format|
      if @user.update(new_user_params)

        #para que no se salga de la cuenta cuando se edita la propia contraseña
        #sign_in(super_admin, :bypass => true)
        format.html { redirect_to :back }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  def root_router
    if current_user.super_admin
      redirect_to projects_path
    elsif current_user.is_boss
      redirect_to enterprise_projects_path(current_user.enterprise)
    else
      redirect_to current_user_path
    end
  end

  def user_params
    params.require(:user).permit(:name, :last_name, :email, :password, :password_confirmation, :enterprise_id)
  end

  private
  def assign_project(project_id)
    if project_id
    @user.projects << Project.find(project_id)
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper

	def roles_array(my_role)
		if my_role == "super_admin"
			[['Super Administrador', 'super_admin'], ['Administrador', 'admin'], ['Last Planner', 'last_planner'], ['Observador', 'observer']] 
		elsif my_role == "admin"
			[['Administrador', 'admin'], ['Last Planner', 'last_planner'], ['Observador', 'observer']] 
		end
	end
end

app/views/users/_form.html.erb
<%= bootstrap_form_for(@user) do |f| %>


  <%= f.text_field :name, :required => true, :label => 'Nombre' %>
  <%= f.text_field :last_name, :required => true, :label => 'Apellido' %>
  <%= f.text_field :email, :required => true, :label => 'Email' %>
  <%= f.password_field :password, :required => true, :label => 'Contraseña' %>
  <%= f.password_field :password_confirmation, :required => true, :label => 'Confirmar contraseña' %>
  <%= f.hidden_field :enterprise_id, value: @user.enterprise_id %>
  <%= f.submit %>
<% end %>

app/views/users/_form_assign_project.html.erb
<h1>Asignar usuario a proyectos</h1>

<%= form_tag(assign_to_project_user_path, method: "post") do %>
  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Nombre</th>
        </tr>
      </thead>
      <tbody>
      <% @projects.each do |project| %>
      <tr>
        <td class="td1">

          <%= check_box("tag", project.id, { checked: @user.projects.include?(project)}) %>
          <%= project.name %>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
</div>

  <%= submit_tag("Asignar") %>
<% end %>






<br>

app/views/users/_form_edit.html.erb
<!--vista para que el super admin cree un nuevo usuario-->
<div class="form_modal">
<table>
  <tr>
    <td class="supform"><h3>Editar Usuario</h3></td>
  </tr>
  <tr><td class="space"></td></tr>
  <tr>
    <td>
    <%= bootstrap_form_for(@user, layout: :horizontal) do |f| %>

    <!--se piden los campos-->
      <div class="field">
        <%= f.text_field :name, :required => true, :label => 'Nombre' %>
      </div>
     <div class="field">
        <%= f.text_field :email, :required => true, :label => 'Correo' %>
      </div>
      <div class="field">
        <%= f.text_field :password, :required => true, :label => 'Contraseña' %>
      </div>
    <!--drop down menu para roles, donde el 1er string es lo que se muestra y el 2do es lo que se guarda en la bd-->
      <div class="field">
        <% if can? :create, User %>
            <%= f.select :role, options_for_select(roles_array(current_user.role)), :label => 'Rol'%>         
      <% end %>
      </div>
      <div class="actions">
        <%= f.submit "Guardar Cambios" %>
      </div>
    <% end %>
    </td>
  </tr>
</table>
</div>

app/views/users/_index_for_enterprise.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Usuarios de <%= @enterprise.name %></h1>
  </div>
</div>


<div class="row">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @enterprise.users.each do |u| %>
          <!-- Si es el mismo usuario, no se muestra -->
          <% if u != current_user %>
            <tr>
              <td><%= u.f_name %></td>
              <td><%= link_to 'Detalles', u %></td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to_modal 'Nuevo usuario para ' + @enterprise.name , new_user_path(enterprise_id: @enterprise.id) %>
  </div>
</div>

app/views/users/_index_for_project.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Usuarios de <%= @project.name %></h1>
  </div>
</div>


<div class="row">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @project.assignments.each do |a| %>
          <tr>
            <td><%= a.user.f_name %></td>
            <td><%= link_to 'eliminar asignación', a, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to_modal 'Asignar este proyecto a un usuario', new_assignment_path(project_id: @project.id) %>
  </div>
</div>

app/views/users/_users_table.html.erb
<div class="container">
  <h1>Usuarios</h1>

  <div class="table-responsive">
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="col-lg-3">Nombre</th>
          <th class="col-lg-2">Email</th>
          <th class="col-lg-1"></th>                   
        </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
       <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to 'X', user, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
        </tr>
      <% end %>
      </tbody>
    </table>      
  </div>
</div>

<br>

app/views/users/assign.html.erb
<%= render 'form_assign_project' %>

<%= link_to 'Atrás', users_path %>

app/views/users/edit.html.erb
<h1><%= current_user.name %></h1>
<%= render 'form' %>

app/views/users/index.html.erb
<% if @project %>
  <%= render 'index_for_project' %>
<% elsif @enterprise %>
  <%= render 'index_for_enterprise' %>
<% end %>

app/views/users/new.html.erb
<h1>Crear Usuario</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
	<div class="col-md-12">
		<h1><%= @user.f_name %></h1>
	</div>
</div>


<div class="row">
	<div class="col-md-12">
		<h2>Proyectos</h2>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<table class="table">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Rol en el proyecto</th>
					<th></th>
				</tr>
			</thead>
		<% @user.assignments.each do |a| %>
			<tr>
				<td><%= a.project.name %></td>
				<td><%= a.f_role %></td>
				<td><%= link_to 'Editar asignación', edit_assignment_path(a) %></td>
			</tr>
		<% end %>
		</table>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= link_to_modal 'Asignar un proyecto a este usuario' , new_assignment_path(user_id: @user.id)%>
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		<%= link_to_modal 'Editar perfil', edit_user_path(current_user)%>
	</div>
</div>