config/routes.rb
######API#######
require 'api_constraints'

Rails.application.routes.draw do


  #Aquí creamos rutas para proveer la API de la aplcación, para ver más detalles acceder a:
    # http://railscasts.com/episodes/350-rest-api-versioning?view=asciicast
  namespace :api, defaults: {format: 'json'} do

    #Archivos relevantes para la API
    ## /lib/api_constraints
    ## /app/controllers/api  (todo lo que esta dentro de esa carpeta)

    # Para la version 1 tenemos este bloque con api constraints especificamos la versión
    # y si es que esta es la que se ocupa por default
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      #Aquí defeinimos las rutas que queremos proveer
      #por ahora tenemos disponibles los proyectos, tareas y login de usuario
      get '/locks/all' => 'locks#all'
      resources :projects, only: [:index] do
        resources :tasks, only: [:index,:update,:show] do
          get 'all', on: :collection
          put 'update_gantt', on: :member, action:'update_gantt'
          delete 'update_gantt', on: :member, action:'destroy'
          post 'update_gantt', on: :collection, action:'create'
          resources :comments, only: [:create]
        end
        get 'all', on: :collection
      end

      #Métodos para usuarios
      post 'users/login', to: 'users#login'
      delete 'users/logout', to: 'users#logout'

      #Métodos de progresos
      get '/progress/estimated_in_resources_by_week' 
      get '/progress/real_in_resources_by_week' 
      get '/progress/estimated_in_days_by_week'
      get '/progress/real_in_days_by_week' 
      get '/progress/all_progress'

      get '/progress/performance_in_resources_by_week'
      get '/progress/performance_in_one_by_week'
      post '/push/send_token'

      
      get '/progress/performance_estimated_by_week'
      get '/progress/performance_real_by_week'

    end
  end

#######termino API#####
  
  # Página de errores
  get 'errors/file_not_found'
  get 'errors/unprocessable'
  get 'errors/internal_server_error'
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all


  #usuarios con gema devise
  devise_for :users


  #Resources genera todas las rutas CRUD para cada uno de estos objetos
  resources :projects do
    get 'delete'
    get 'second_indicators'
    get 'tree_view'
    get 'add_tree_view_column'
    get 'indicators'
    get 'export'
    get 'kanban_board', to: 'kanban_board#index', as: :kanban_board_index
    get 'gantt', to: 'gantt#index'

    resources :users, only: [:index]
    resources :tasks do
      resources :reports
      resources :comments

    end
  end

  resources :tasks do
    get 'delete_confirmation'
    get 'fast_report'
  end

  get 'gantt', to: 'gantt#index'
  get 'update_tree_view', to: 'tasks#update_tree_view'
  
  # get 'kanban_board_index', to: 'kanban_board#index'
  get 'gantt', to: 'gantt#index'

  resources :comments
  resources :reports
  resources :assignments
  resources :users



  resources :enterprises do
    resources :projects
    resources :users
  end

  namespace :kanban_board do
    get 'index'
    get 'update_item_partial'
  end




  root 'users#root_router'
end

app/controllers/api/v1/projects_controller.rb
#Aquí definimos las respuestas a las llamadas de la api
module Api
  module V1
    class ProjectsController < ActionController::Base
      before_filter :restrict_access, only: [:index]
      before_action :set_user, only: [:index]
      #Con esto definimos como queremos entregar la respuesta.
      respond_to :json

      def index
        @projects = @user.projects
        respond_with @projects
      end


      def all
        @projects = User.find(current_user).projects
        render :file => "api/v1/projects/all.json.jbuilder",
               :content_type => 'application/json'
      end


      private
       def restrict_access
        token=request.headers["Authorization"]
        set_api_key(token)
        if @ak
          unless @ak.valid_token
            @ak.destroy
          end
        end
        unless ApiKey.exists?(access_token: token)
          render nothing: 'HTTP_ACCESS_DENIED', status: '403'
        end
      end

      def set_user
        token = request.headers["Authorization"]
        set_api_key(token)
        @user = @ak.user if @ak
      end

      def set_api_key(token)
        @ak = ApiKey.find_by_access_token(token)
      end
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource

  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if current_user.super_admin
      @projects = Project.all
    elsif current_user.enterprise.boss == current_user
      @projects = current_user.enterprise.projects
    else
      @projects = current_user.projects
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    
  end

  def second_indicators
    
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end


  # POST /projects
  # POST /projects.json

  def create
    @project = Project.new(project_params)

    if params[:project][:xml_file]
      i = Importer.new(params[:project][:xml_file])
      i.import(@project)
    end

    respond_to do |format|
      if @project.save
        format.html { redirect_to request.referer }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # vista de confirmacion
  def delete
    @project = Project.find(params[:project_id])    
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    #cuando se borra un proyecto borrar también el archivo xml
    if @project.xml_file and File.exist?(@project.xml_file)
      File.delete(@project.xml_file)
    end
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  # metodo asociado a la vista de arbol de un proyecto y sus tareas
  def tree_view
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html
      format.js
    end

  end

  # Metodo asociado a la vista de la carta gantt de un proyecto
  def gantt
    @project = Project.find(params[:project_id])
  end

  # Metodo asociado a la vista de indicadores de un proyecto
  def indicators
    @project = Project.find(params[:project_id])
  end

  def export
    project = Project.find(params[:project_id])
    e = Exporter.new(project)
    begin
      hash = e.export
      path = "#{project.name.gsub(' ', '_').camelize}.xml"
      f = File.open(path, "w")
      p "Writing file.."
      f.write(hash["Project"].to_xml(:root => 'Project', skip_types: true))
      send_file(f, disposition:'attachment')
      f.close
      p "File ready!"
    rescue
      flash[:alert] = "No se pudo exportar."
      redirect_to project_path(project)
    end
  end

  def add_tree_view_column
    # tarea de la cual se desplegaran sus hijos en una nueva columna del arbol
    @task = Task.find(params[:parent_id])
    @project = Project.find(params[:project_id])
    respond_to do |format|
      format.js
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :start_date, :end_date, :expected_start_date, :expected_end_date, :xml_file, :resources_type, :resources_reporting, :enterprise_id)
  end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= bootstrap_form_for(@project) do |f| %>

  <!-- NOMBRE -->
  <%= f.text_field :name, :required => true, :label => 'Nombre *' %>

  <!-- FECHA DE INICIO -->
  <%= f.date_select :expected_start_date, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, :required => true, :label => 'Fecha de Inicio' %>

  <!-- FECHA DE TERMINO -->
  <%= f.date_select :expected_end_date, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, :required => true, :label => 'Fecha de Término' %>

  <!-- TIPO DE RECURSOS     -->
  <%= f.select :resources_type, [['Seleccionar', ''],['Tiempo', 0], ['Dolares', 1], ['UF', 2], ['Horas Hombres', 3]], :label => 'Tipo de Recursos' %>

  <!-- REPORTAR AVANCES EN TIEMPO REAL -->
  <%= f.select :resources_reporting, [['Seleccionar', false], ['Quiero reportar en tiempo real el uso de recursos', true], ['No quiero reportar en tiempo real el uso de recursos', false]], :label => 'Reportar Recursos' %>

  <!-- IMPORTACIÓN -->
  <%= f.file_field :xml_file , :label => 'Importar (Opcional)', :accept =>'text/xml' %>

  <!-- EMPRESA -->
  <%= f.hidden_field :enterprise_id, value: @enterprise.id %>

  <%= f.submit "Crear Proyecto" %>
<% end %>
 

app/views/projects/_form_edit.html.erb
<div class="form_modal">
<table>
  <tr><td class="supmodal"><h3>Editar Proyecto</h3></td></tr>
  <tr><td class="space"></td></tr>
  <tr>
    <td>
    <%= bootstrap_form_for(@project, layout: :horizontal) do |f| %>
      <% if @project.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
          <% @project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.text_field :name, :required => true, :label => 'Nombre' %>
      </div>
      <div class="field">
        <%= f.date_select :start_date, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, :required => true, :label => 'Fecha de Inicio' %>
      </div>
      <div class="field">
        <%= f.date_select :end_date, {:use_month_names => ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre','Diciembre']}, :required => true, :label => 'Fecha de Término' %>
      </div>
      <div class="field">
        <%= f.select :resources, [['Seleccionar', false], ['Quiero incluir recursos a mi proyecto', true], ['No quiero incluir recursos a mi proyecto', false]], :label => 'Recursos *' %>
      </div>
      <div class="field">
        <%= f.select :type_resources, [['Seleccionar', ''],['Pesos', 'Pesos'], ['Dolares', 'USD'], ['UF', 'UF'], ['Horas Hombres', 'HH']], :label => 'Tipo de Recursos' %>
      </div>
       <div class="field">
        <%= f.select :report, [['Seleccionar', false], ['Quiero reportar en tiempo real el uso de recursos', true], ['No quiero reportar en tiempo real el uso de recursos', false]], :label => 'Reportar Recursos' %>
      </div>
      <div class="actions">
        <%= f.submit "Guardar Cambios" %>
      </div>
    <% end %>
    </td>
  </tr>
</table>
  
</div>

app/views/projects/_gant_tree_view_sub_menu.html.erb
<div class="full horizontal_sub_menu">
	<table>
		<tr>
			<td class="<%= 'active' if params[:action] == 'gantt' %>"><%= link_to 'Gantt', project_gantt_path(@project)%></td>
			<td class="<%= 'active' if params[:action] == 'tree_view' %>"><%= link_to 'Explorador', project_tree_view_path(@project)%></td>
		</tr>
	</table>
</div>

app/views/projects/_info.html.erb
<div class="col-md-6">
  <table class="table table-striped">
    <thead>
      <tr>
        <th class="col-lg-5" colspan="2">Informacion del proyecto</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Fecha inicio</td>
        <td><%= @project.f_start_date %></td>
      </tr>
      <tr>
        <td>Fecha término</td>
        <td><%= @project.f_end_date %></td>
      </tr>
      <tr>
        <td>Progreso</td>
        <td><%= @project.info_progress_as_percentaje[0] %></td>
      </tr>
      <tr>
        <td>Progreso estimado</td>
        <td><%= @project.info_progress_as_percentaje[1] %></td>
      </tr>
      <tr>
        <td>Número de tareas</td>
        <td><%= link_to @project.tasks.count, project_tasks_path(@project) %></td>
      </tr>
      <tr>
        <td>Recursos?</td>
        <td><%= @project.info_project_resources(@project.resources) %></td>
      </tr>
      <% if @project.resources %>
      <tr>
        <td>Tipo de Recursos</td>
        <td><%= @project.type_resources %></td>
      </tr>
      <tr>
        <td>Reportar?</td>
        <td><%= @project.info_project_resources(@project.report) %></td>
      </tr>
      <tr>
        <td>Costo Total</td>
        <td><%= number_with_delimiter(@project.cost_total_project(@project.resources).round) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/projects/_users.html.erb
<div class="col-md-6">
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th class="col-lg-5" colspan="2">Usuarios</th>
        </tr>
      </thead>
      <tbody>
      <% @project.users.each do |u| %>
        <tr>
          <td><%= u.name %></td>
          <td><%= u.role_u %></td>          
        </tr>
      <% end %>
      </tbody>
    </table>      
  </div>
</div>

app/views/projects/add_tree_view_column.js.erb
$(function(){

	//Removemos todas las columnas despues de la clickeada
	$('#column_<%= @task.parent_id ? @task.parent_id : 0 %>').nextAll().remove();

	// Removemos el atributo active de class de todos los items de la columna clickeada
	$('#column_<%= @task.parent_id ? @task.parent_id : 0 %>').find('.item .arrow').removeClass('active');

	//Al item clickeado lo dejamos active
	$('#item_<%= @task.id %> .arrow').addClass('active');

	//Agregamos el partial column a tree view via append, escape_javascript
	$('#tree_view_content').append('<%= escape_javascript(render "projects/explorer/tree_view_column", parent: @task) %>');

	// Nos movemos hacia el final de la div tree view para ver completa la columna recien agregada
	$('#tree_view').animate( { scrollLeft: '+=500' }, 500, 'easeOutQuad' );
});

app/views/projects/edit.html.erb
<h1>Editando Proyecto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @project %> |
<%= link_to 'Atrás', projects_path %>

app/views/projects/gantt.html.erb
<%= render 'gantt/show'%>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Proyectos</h1>
  </div>
</div>


<div class="row">
  <div class="col-md-12">
    <table class="table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Recursos</th>
          <th>Avance</th>
          <th>Avance esperado</th>
          <th>Inicio esperado</th>
          <th>Término esperado</th>
          <th>Fecha inicio</th>
          <th>Fecha término</th>
          <th>Ultimo reporte</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |p| %>
          <tr>
            <td><%= link_to p.name, p %></td>
            <td><%= p.f_resources_type %></td>
            <td><%= p.progress.to_f %> %</td>
            <td><%= p.expected_progress.to_f %> %</td>
            <td><%= f_date(p.expected_start_date) %></td>
            <td><%= f_date(p.expected_end_date) %></td>
            <td><%= f_date(p.start_date) %></td>
            <td><%= f_date(p.end_date) %></td>
            <% if p.last_report %>
              <td><%= f_date(p.last_report.created_at) %> <br> <%= p.last_report.user ? p.last_report.user.f_name : 'Importación' %></td>
            <% else %>
              <td></td>
            <% end %>
            <% if current_user.can_edit_project(p) %>
              <td><%= link_to_modal 'X', project_delete_path(p) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% if current_user.is_boss %>
  <div class="row">
    <div class="col-md-12">
      <%= link_to_modal 'Nuevo proyecto', new_enterprise_project_path(@enterprise) %>
    </div>
  </div>
<% end %>

app/views/projects/indicators.html.erb
<%= render 'indicators/show'%>

app/views/projects/new.html.erb
<h1>Nuevo Projecto</h1>

<%= render 'form' %>

app/views/projects/second_indicators.html.erb
<div class="row">
	<div id="demo_chart" class="col-md-12">

	</div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1><%= @project.name %></h1>
  </div>
</div>

<% if current_user.can_edit_project(@project) %>
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Exportar', project_export_path(@project) %>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'Usuarios', project_users_path(@project) %>
  </div>
</div>

app/views/projects/tree_view.html.erb
<div id="tree_view">
	<!-- Header de la vista explorador (tree_view) 	 -->
	<%= render 'projects/explorer/tree_view_header'%>
	
	<div class="full" id="tree_view_content">
		<!-- Se crea una columna inicial que corresponde a las tareas de primer nivel -->
		<%= render 'projects/explorer/tree_view_column', parent: @project %>
	</div>
</div>